// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MockService exposes mock-only controls to the F1 and F2 screens. Reads
 * remain on the common screen-facing services so mock and Azure paths use the
 * same data contract.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetModelScenario keeps the F2 control in sync when the browser reloads.
 */
export function GetModelScenario(): $CancellablePromise<string> {
    return $Call.ByID(739599049);
}

/**
 * GetScenario keeps the controls in sync when the browser reloads.
 */
export function GetScenario(): $CancellablePromise<string> {
    return $Call.ByID(1672750476);
}

/**
 * SetModelScenario changes the response used by the next F2 read.
 */
export function SetModelScenario(name: string): $CancellablePromise<void> {
    return $Call.ByID(1651976165, name);
}

/**
 * SetScenario changes the response used by the next read.
 */
export function SetScenario(name: string): $CancellablePromise<void> {
    return $Call.ByID(94244952, name);
}
