// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MockService exposes mock-only controls to the F1 screen. The deployment
 * read itself remains on service.DeploymentService so mock and Azure paths use
 * the same screen-facing contract.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetScenario keeps the controls in sync when the browser reloads.
 */
export function GetScenario(): $CancellablePromise<string> {
    return $Call.ByID(1672750476);
}

/**
 * SetScenario changes the response used by the next read.
 */
export function SetScenario(name: string): $CancellablePromise<void> {
    return $Call.ByID(94244952, name);
}
