// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MockService exposes mock-only controls to the F1 and F2 screens. Reads
 * remain on the common screen-facing services so mock and Azure paths use the
 * same data contract.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetAddModelScenario keeps the model addition control in sync on reload.
 */
export function GetAddModelScenario(): $CancellablePromise<string> {
    return $Call.ByID(1836044536);
}

/**
 * GetCreateScenario keeps the creation-result control in sync on reload.
 */
export function GetCreateScenario(): $CancellablePromise<string> {
    return $Call.ByID(327907264);
}

/**
 * GetModelScenario keeps the F2 control in sync when the browser reloads.
 */
export function GetModelScenario(): $CancellablePromise<string> {
    return $Call.ByID(739599049);
}

/**
 * GetScenario keeps the controls in sync when the browser reloads.
 */
export function GetScenario(): $CancellablePromise<string> {
    return $Call.ByID(1672750476);
}

/**
 * SetAddModelScenario changes the response used by the next addition read.
 */
export function SetAddModelScenario(name: string): $CancellablePromise<void> {
    return $Call.ByID(1029536492, name);
}

/**
 * SetCreateScenario changes the creation result reproduced by the next add.
 */
export function SetCreateScenario(name: string): $CancellablePromise<void> {
    return $Call.ByID(2192600564, name);
}

/**
 * SetModelScenario changes the response used by the next F2 read.
 */
export function SetModelScenario(name: string): $CancellablePromise<void> {
    return $Call.ByID(1651976165, name);
}

/**
 * SetScenario changes the response used by the next read.
 */
export function SetScenario(name: string): $CancellablePromise<void> {
    return $Call.ByID(94244952, name);
}
