// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CreationService is the screen-facing service for adding a model. Writing is
 * deliberately separate from the read services: it records an operation before
 * every request and never retries a request on its own.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddModel performs one confirmed addition. It returns the observed outcome;
 * it does not resend a request whose result is unknown.
 */
export function AddModel(request: $models.CreateRequest): $CancellablePromise<$models.CreateResult> {
    return $Call.ByID(918022692, request).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CheckOperation re-reads the state of one recorded operation. It only reads:
 * nothing is created, resent or deleted.
 */
export function CheckOperation(operationID: string): $CancellablePromise<$models.CreateResult> {
    return $Call.ByID(817106125, operationID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PendingOperations lists the operations whose result is still unsettled, so the
 * screen can show them after a restart instead of silently continuing.
 */
export function PendingOperations(): $CancellablePromise<$models.PendingOperation[]> {
    return $Call.ByID(3658431205).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CreateResult.createFrom;
const $$createType1 = $models.PendingOperation.createFrom;
const $$createType2 = $Create.Array($$createType1);
