// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeploymentService is the screen-facing service for the F1 deployment list.
 * The fetch function is the boundary to Azure (or the deterministic mock).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDeployments obtains one snapshot from the configured boundary.
 */
export function GetDeployments(requestID: string): $CancellablePromise<$models.DeploymentResult> {
    return $Call.ByID(644167374, requestID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetEnvironment tells the screen whether this service is backed by the
 * deterministic F1 data source.
 */
export function GetEnvironment(): $CancellablePromise<$models.Environment> {
    return $Call.ByID(889756815).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DeploymentResult.createFrom;
const $$createType1 = $models.Environment.createFrom;
