// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelService is the screen-facing service for F2 model candidates. The
 * fetch function is the boundary to Azure (or the deterministic mock).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetModels obtains the model candidates for one F1 account row.
 */
export function GetModels(accountID: string): $CancellablePromise<$models.ModelResult> {
    return $Call.ByID(4271855494, accountID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetRegionModels obtains the candidates a subscription can deploy in one
 * region. It serves a Foundry that does not exist yet, so the result is
 * provisional and must be confirmed against the created account before use.
 */
export function GetRegionModels(subscriptionID: string, region: string): $CancellablePromise<$models.ModelResult> {
    return $Call.ByID(818870930, subscriptionID, region).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ModelResult.createFrom;
