// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlacementService is the screen-facing service for choosing where a model is
 * added. It only reads; creating a resource group or Foundry is not part of it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDeploymentNames reads the deployment names of one Foundry so the screen can
 * reject a name that already exists in that exact Foundry.
 */
export function GetDeploymentNames(accountID: string): $CancellablePromise<$models.DeploymentNameResult> {
    return $Call.ByID(1028359543, accountID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetPlacements reads the subscriptions, resource groups and Foundries the
 * signed-in account can add a model to.
 */
export function GetPlacements(): $CancellablePromise<$models.PlacementResult> {
    return $Call.ByID(3136154262).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DeploymentNameResult.createFrom;
const $$createType1 = $models.PlacementResult.createFrom;
